### ISSUE TITLE
Mac Makefile error

### ISSUE THREAD

**Issue by DrewRWx** [wolftype/versor_1.0#2]
On Mountain Lion I'm having an issue running the Makefile: Makefile.common:188: **\* extraneous `else'.  Stop.

I looked into it, but my make knowledge is a bit rusty, so I couldn't find any issues.

Thank you,
Drew

**Comment by wolftype** [comment]
Thanks Drew, this should now be fixed -- please let me know if not.  I only have Lion to test on (not Mountain Lion).

**Comment by DrewRWx** [comment]
Sorry I didn't see this sooner, my employer floods my GitHub notifications.

The makefile change fixed that issue, but another came up: 
  I can compile examples in the vsr directory, but running `make examples/allovsr/hopf.cpp`
  in the AlloSystem directory returns `build//include/vsr/vsr.h:24:18: fatal error: Rot.h: No such file or directory`.

  If I add `Element/` to `#include "Rot.h"`, compilation fails on `#include "vsr_casts.h"` in `Rot.h`.

Cheers,
Drew

**Comment by wolftype** [comment]
Did you run "make vsr" from within the allosystem repo (not just within vsr repo)?  That command copies all the headers into allosystem/build/

---

Pablo Colapinto
Media Arts and Technology Program
University of California, Santa Barbara

**Comment by wolftype** [comment]
Also , try 

cd allosystem
make vsr
make allovsr
cd allovsr
make examples....

---

Pablo Colapinto
Media Arts and Technology Program
University of California, Santa Barbara

**Comment by DrewRWx** [comment]
I did run `make vsr` and `make allovsr` from inside the AlloSystem directory. Compiling and running the examples works from the `allovsr/examples` directory, but they give the error message if the symlink to the `allovsr` examples in `AlloSystem/examples` is used.

**Comment by wolftype** [comment]
Gotcha.  I'll work on that.  Let's move this issue over to the allosystem repo though, since it is an issue with our make system there (not with the versor library).

---

Pablo Colapinto
Media Arts and Technology Program
University of California, Santa Barbara
